2019-09-07 14:48:18,396 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:51:44,157 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:51:49,162 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:51:54,980 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:51:57,173 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:51:58,834 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:52:39,557 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 14:52:46,076 [django.request:135] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /deletemessageapi/
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 219, in dispatch
    return super(DeleteMessageApi, self).dispatch(*args, **kwargs)
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "H:\python学习笔记\Django框架的运用\Django用户认证+Restframe Work\UserSystem\userapp\views.py", line 222, in get
    a = 1/0
ZeroDivisionError: division by zero
2019-09-07 15:09:51,173 [django:227] [views:get] [INFO]- 一条提示信息
2019-09-07 15:09:51,177 [django.server:124] [basehttp:log_message] [INFO]- "GET /deletemessageapi/ HTTP/1.1" 200 58
2019-09-07 15:09:54,929 [django:227] [views:get] [INFO]- 一条提示信息
2019-09-07 15:09:54,932 [django.server:124] [basehttp:log_message] [INFO]- "GET /deletemessageapi/ HTTP/1.1" 200 58
2019-09-07 15:09:55,970 [django:227] [views:get] [INFO]- 一条提示信息
2019-09-07 15:09:55,973 [django.server:124] [basehttp:log_message] [INFO]- "GET /deletemessageapi/ HTTP/1.1" 200 58
2019-09-07 20:54:58,005 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 20:54:58,415 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:54:58,417 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:54:58,477 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:54:58,554 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-07 20:54:58,589 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:54:58,632 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-07 20:54:58,656 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-07 20:54:58,664 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:54:58,676 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:54:58,689 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:54:58,791 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:54:58,824 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:54:58,846 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:54:58,871 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:54:58,883 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:54:58,950 [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 85
2019-09-07 20:57:44,173 [django:227] [views:get] [INFO]- 一条提示信息
2019-09-07 20:57:44,188 [django.server:124] [basehttp:log_message] [INFO]- "GET /deletemessageapi/ HTTP/1.1" 200 58
2019-09-07 20:57:49,077 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 20:57:49,142 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-07 20:57:49,151 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-07 20:57:49,158 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:57:49,164 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-07 20:57:49,176 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:57:49,193 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:57:49,200 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:57:49,206 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:57:49,211 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:57:49,216 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:57:49,275 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:57:49,289 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:57:49,307 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:57:49,326 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:57:49,343 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:57:53,499 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:57:53,499 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-07 20:57:53,505 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-07 20:57:53,506 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-07 20:58:01,969 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:58:34,688 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 20:58:34,790 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-07 20:58:34,798 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:58:34,809 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-07 20:58:34,825 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-07 20:58:34,835 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:58:34,845 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:58:34,846 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:58:34,861 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:58:34,861 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:58:34,869 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:58:34,978 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:58:35,049 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:58:35,070 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:58:35,081 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:58:35,093 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:58:35,106 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:58:37,150 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 20:58:37,263 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-07 20:58:37,264 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:58:37,289 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-07 20:58:37,308 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-07 20:58:37,330 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:58:37,332 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:58:37,374 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:58:37,386 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:58:37,434 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:58:37,464 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:58:37,481 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:58:37,547 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:58:37,578 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:58:37,609 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:58:37,667 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:58:55,325 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 20:58:55,391 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-07 20:58:55,418 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:58:55,437 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-07 20:58:55,477 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-07 20:58:55,487 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:58:55,503 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:58:55,527 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:58:55,543 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:58:55,554 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:58:55,578 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:58:55,583 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-07 20:58:55,650 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-07 20:58:55,684 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-07 20:58:55,703 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-07 20:58:55,767 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-07 20:58:55,783 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-07 20:59:10,107 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-07 20:59:33,807 [django.db.backends:91] [utils:execute] [DEBUG]- (0.003) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2019-09-07 20:59:33,812 [django.db.backends:91] [utils:execute] [DEBUG]- (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2019-09-07 20:59:34,992 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2019-09-07 20:59:38,433 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 20:59:38,516 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2019-09-07 20:59:38,517 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2019-09-07 20:59:38,518 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
2019-09-07 20:59:38,533 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2019-09-07 20:59:38,546 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2019-09-07 20:59:38,582 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2019-09-07 20:59:38,603 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
2019-09-07 20:59:38,629 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
2019-09-07 20:59:38,649 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
2019-09-07 20:59:38,831 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2019-09-07 21:03:33,537 [django.db.backends:91] [utils:execute] [DEBUG]- (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2019-09-07 21:03:33,541 [django.db.backends:91] [utils:execute] [DEBUG]- (0.001) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2019-09-07 21:04:11,167 [django.db.backends:91] [utils:execute] [DEBUG]- (0.002) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2019-09-07 21:04:11,172 [django.db.backends:91] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2019-09-07 21:05:08,545 [django.db.backends:91] [utils:execute] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2019-09-07 21:05:08,555 [django.db.backends:91] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2019-09-07 21:05:30,588 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 21:05:31,104 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 121
2019-09-07 21:05:39,895 [django.server:124] [basehttp:log_message] [WARNING]- "GET /dsadassadsa HTTP/1.1" 404 85
2019-09-07 21:06:42,410 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-07 21:06:51,118 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000139466EA518>}"
2019-09-07 21:06:51,120 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000139466EA518>}"
2019-09-07 21:06:51,121 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x00000139466EA518>}"
2019-09-07 21:06:51,150 [django.server:124] [basehttp:log_message] [INFO]- "GET /xxx/ HTTP/1.1" 200 14731
2019-09-07 21:06:53,708 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001394674B0B8>}"
2019-09-07 21:06:53,712 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001394674B0B8>}"
2019-09-07 21:06:53,713 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x000001394674B0B8>}"
2019-09-07 21:06:53,737 [django.server:124] [basehttp:log_message] [INFO]- "GET /xxx/?page=2 HTTP/1.1" 200 14405
2019-09-07 21:06:55,301 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000013946741400>}"
2019-09-07 21:06:55,305 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000013946741400>}"
2019-09-07 21:06:55,307 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000013946741400>}"
2019-09-07 21:06:55,331 [django.server:124] [basehttp:log_message] [INFO]- "GET /xxx/ HTTP/1.1" 200 14731
2019-09-07 21:06:57,657 [django.server:124] [basehttp:log_message] [INFO]- "GET /article_post_detail/owner/11/ HTTP/1.1" 200 10499
2019-09-07 21:07:04,334 [django.server:124] [basehttp:log_message] [INFO]- "GET /article_post_detail/owner/10/ HTTP/1.1" 200 10721
2019-09-07 21:07:06,651 [django.server:124] [basehttp:log_message] [INFO]- "GET /article_post_detail/owner/10/ HTTP/1.1" 200 10721
2019-09-07 21:07:08,799 [django.server:124] [basehttp:log_message] [INFO]- "GET /article_post_detail/owner/10/ HTTP/1.1" 200 10721
2019-09-07 21:07:12,240 [django.server:124] [basehttp:log_message] [INFO]- "GET /article_post_detail/owner/10/ HTTP/1.1" 200 10721
2019-09-07 21:07:14,885 [django.server:124] [basehttp:log_message] [INFO]- "GET /article_post_detail/owner/10/ HTTP/1.1" 200 10721
2019-09-08 10:02:11,031 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-08 10:02:11,352 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-08 10:02:11,354 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-08 10:02:11,383 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-08 10:02:11,441 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-08 10:02:11,496 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-08 10:02:11,507 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-08 10:02:11,514 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-08 10:02:11,545 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-08 10:02:11,565 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-08 10:02:11,570 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-08 10:02:11,578 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-08 10:02:11,601 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-08 10:02:11,614 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-08 10:02:11,624 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-08 10:02:11,645 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-08 10:02:11,654 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-08 10:02:11,670 [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 85
2019-09-08 10:02:15,406 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-08 10:02:15,457 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-08 10:02:15,464 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-08 10:02:15,467 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-08 10:02:15,479 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-08 10:02:15,488 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-08 10:02:15,501 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-08 10:02:15,508 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-08 10:02:15,514 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-08 10:02:15,537 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-08 10:02:15,566 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-08 10:02:15,567 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-08 10:02:15,587 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-08 10:02:15,637 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-08 10:02:15,661 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-08 10:02:15,675 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-08 10:02:15,688 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-08 10:02:21,908 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-08 10:02:22,819 [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 85
2019-09-08 10:02:48,220 [django:231] [views:get] [INFO]- 来自IP地址为:127.0.0.1的请求
2019-09-08 10:02:48,229 [django.server:124] [basehttp:log_message] [INFO]- "GET /deletemessageapi/ HTTP/1.1" 200 58
2019-09-08 10:04:20,230 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-08 10:04:20,353 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-08 10:04:20,365 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-08 10:04:20,385 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-08 10:04:20,418 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-08 10:04:20,430 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-08 10:04:20,438 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-08 10:04:20,438 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-08 10:04:20,445 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-08 10:04:20,446 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-08 10:04:20,467 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-08 10:04:20,590 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 404 118
2019-09-08 10:04:20,608 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 404 111
2019-09-08 10:04:20,621 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 404 106
2019-09-08 10:04:20,651 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 404 115
2019-09-08 10:04:20,661 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 404 114
2019-09-08 10:04:20,676 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/js/default.js HTTP/1.1" 404 109
2019-09-08 10:04:20,688 [django.server:124] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 85
2019-09-08 10:04:26,657 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 404 117
2019-09-08 10:04:26,659 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 404 120
2019-09-08 10:04:26,664 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 404 112
2019-09-08 10:04:26,676 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/default.css HTTP/1.1" 404 111
2019-09-08 10:08:34,151 [django.db.backends:91] [utils:execute] [DEBUG]- (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
2019-09-08 10:08:34,154 [django.db.backends:91] [utils:execute] [DEBUG]- (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
2019-09-08 10:08:43,881 [django.server:124] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 9645
2019-09-08 10:08:43,958 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
2019-09-08 10:08:43,976 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
2019-09-08 10:08:43,976 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
2019-09-08 10:08:43,980 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
2019-09-08 10:08:44,007 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
2019-09-08 10:08:44,032 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
2019-09-08 10:08:44,058 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
2019-09-08 10:08:44,099 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
2019-09-08 10:08:44,136 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
2019-09-08 10:08:44,150 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37608
2019-09-08 10:08:44,162 [django.server:124] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
2019-09-08 10:08:44,233 [django.server:124] [basehttp:log_message] [WARNING]- "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1733
2019-09-08 10:08:48,112 [django.db.backends:91] [utils:execute] [DEBUG]- (0.002) SELECT "restapp_userarticle"."id", "restapp_userarticle"."created", "restapp_userarticle"."title", "restapp_userarticle"."content", "restapp_userarticle"."owner_id" FROM "restapp_userarticle" LIMIT 21; args=()
2019-09-08 10:08:48,117 [django.db.backends:91] [utils:execute] [DEBUG]- (0.000) SELECT COUNT(*) AS "__count" FROM "restapp_userarticle"; args=()
2019-09-08 10:08:48,118 [django.db.backends:91] [utils:execute] [DEBUG]- (0.000) SELECT "restapp_userarticle"."id", "restapp_userarticle"."created", "restapp_userarticle"."title", "restapp_userarticle"."content", "restapp_userarticle"."owner_id" FROM "restapp_userarticle" LIMIT 2; args=()
2019-09-08 10:08:48,136 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'hide_label' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'hide_label'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [hide_label] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000018C040A62E8>}"
2019-09-08 10:08:48,138 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'placeholder' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'placeholder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [placeholder] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000018C040A62E8>}"
2019-09-08 10:08:48,143 [django.template:925] [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'autofocus' in template 'rest_framework/horizontal/input.html'.
Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 882, in _resolve_lookup
    current = current[bit]
KeyError: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'dict' object has no attribute 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'autofocus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\slipper\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [autofocus] in "{'base_template': 'input.html', 'input_type': 'text', 'template_pack': 'rest_framework/horizontal', 'renderer': <rest_framework.renderers.HTMLFormRenderer object at 0x0000018C040A62E8>}"
2019-09-08 10:08:48,177 [django.server:124] [basehttp:log_message] [INFO]- "GET /xxx/ HTTP/1.1" 200 14731
